# Generated by Django 6.0.6 on 2026-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='銘柄名')),
                ('brewery', models.CharField(blank=True, max_length=100, verbose_name='蔵元')),
                ('sake_type', models.CharField(blank=True, max_length=50, verbose_name='種類（純米・吟醸など）')),
                ('rating', models.IntegerField(default=3, verbose_name='評価（1〜5）')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sake/', verbose_name='写真')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
